{
 "title": "Barman",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server name",
    "query": "label_values(barman_up, server)"
   }
  ]
 },
 "panels": [
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"barman-01:9100\",mountpoint=~\".*barman/$server\"} - node_filesystem_avail_bytes{instance=\"barman-01:9100\",mountpoint=~\".*barman/$server\"}) / node_filesystem_size_bytes{instance=\"barman-01:9100\",mountpoint=~\".*barman/$server\"} * 100",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Last backup age",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "hour(time()- barman_last_backup{server=\"$server\"})"
    }
   ]
  },
  {
   "title": "First backup age",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - barman_first_backup{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Barman errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(barman_up{server=\"$server\"}) - sum(barman_up{server=\"$server\"})"
    }
   ]
  },
  {
   "title": "Available backups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "barman_backups_total{server=\"$server\"} - barman_backups_failed{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Last backup copy time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "barman_last_backup_copy_time{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "barman_backups_failed{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Last backup size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "barman_backups_size{server=\"$server\", number=\"1\"}\n",
     "legendFormat": "Backup size"
    },
    {
     "expr": "barman_backups_wal_size{server=\"$server\", number=\"1\"}\n",
     "legendFormat": "WAL size"
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "expr": "hour(time() - barman_last_backup{server=\"$server\"})"
    }
   ]
  },
  {
   "title": "Backup partition",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"barman-01:9100\",mountpoint=~\".*barman.*\"} - node_filesystem_avail_bytes{instance=\"barman-01:9100\",mountpoint=~\".*barman.*\"}",
     "legendFormat": "used disk space"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"barman-01:9100\",mountpoint=~\".*barman.*\"}",
     "legendFormat": "available disk space"
    }
   ]
  },
  {
   "title": "Number of available backups",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "barman_backups_total{server=\"$server\"} - barman_backups_failed{server=\"$server\"}\n"
    }
   ]
  }
 ]
}